Polishing homepage
cusec/2023 pull request #26
Opened 2022-09-12 04:33 UTC by HakimSkaik

Sign up button & nav bar list align

2022-09-12 04:39 UTC, danielle-dsouza commented
Don't worry about it saying I force pushed! I didn't modify your changes - I just fixed the merge conflicts (by `rebasing` if you're interested). I'll do a proper review tomorrow!

2022-09-14 13:13 UTC, danielle-dsouza requested changes
Hey! This looks like a really good start! 🥳 

1. The navbar doesn't match the figma on larger screens. The space between the `logo` and `Home` should be only slightly larger than the space between `Home` and `Services`. On large screens the `nav items` are almost in the centre of the `navbar!
![Screen Shot 2022-09-14 at 9 01 50 AM](https://user-images.githubusercontent.com/42760127/190161035-fe0344c3-ced5-4e52-826d-7c175582ecee.png)


2. I also left a comment about using our reusable `Button` component.
3. Lastly - the `sign up` button doesn't collapse into the `side nav`


https://user-images.githubusercontent.com/42760127/190163476-7c9dc746-1833-40d1-8373-48e1bb979f82.mov



It stays at the top of the page - it should become the last item in the list [here](https://github.com/cusec/2023/issues/13#issuecomment-1238557264). I was going to say this could be handled in a different issues, but since this effects how we code the button, I think it's easier to do it in this PR instead of making a follow-up PR.

Let me know if you have any questions!

2022-09-14 13:13 UTC, danielle-dsouza commented on src/components/Navbar/Navbar.tsx
> +        <button className="signupbutton">Sign Up</button>
🤔 Actually can you try and use the [Button](https://github.com/cusec/2023/blob/main/src/components/Button/Button.tsx) component. This way the colour gradient and animations will be consistent on our page. This should be like the `Sponsor` button so you can look [here](https://github.com/cusec/2023/blob/69e393ff88d07c6cf2ea05cf42607dd82e575eb8/src/sections/Home/Home.tsx#L31) for inspiration. 

This would remove all the custom CSS (or most of it at least!)

2022-09-14 13:36 UTC, HakimSkaik commented on src/components/Navbar/Navbar.scss
> +.signupbutton {
Thanks for the review! I did not however fully understand what point 1 was, so should the nav items be more centered? Or more to the left? Looking at the figma file, they appear to be shifted towards the logo

2022-09-14 13:46 UTC, danielle-dsouza commented on src/components/Navbar/Navbar.scss
> +.signupbutton {
Yep exactly - shifted more towards the logo

2022-09-14 17:35 UTC, danielle-dsouza commented on src/components/Navbar/Navbar.scss
> +.signupbutton {
Actually I'm so so sorry - we're using pascal case 🤦 so it should be `SignUpButton`. My bad, my bad.

2022-09-14 22:23 UTC, HakimSkaik commented
do we want the button to still be a button inside the hamburger menu or a CusecLink like the others above it?

2022-09-14 22:39 UTC, danielle-dsouza commented
Hmm I imagine they still want it to be a button - but let me know if you don't think it looks good.

2022-09-14 22:44 UTC, HakimSkaik commented
![image](https://user-images.githubusercontent.com/98859282/190275743-80598802-50d8-43fb-b08f-6e78e4bdf8ea.png)
I think it looks neat now, I'll request a review and show it to the designers, it will look odd to have a button under a menu..

2022-09-18 03:58 UTC, HakimSkaik commented
https://user-images.githubusercontent.com/98859282/190885031-aa6fd8f2-197a-42d3-9791-53d492d2fa10.mp4

2022-09-18 20:10 UTC, danielle-dsouza requested changes
Looks so much better! Just the one comment I made earlier, I'm not sure if you addressed it! Did you try using the `Button` component? Is there a reason it didn't work?

2022-09-18 20:57 UTC, HakimSkaik commented
Yes! But then I couldn't animate the button the way it is now..

2022-09-19 18:15 UTC, HakimSkaik commented
This pr was fixed yesterday, can we merge it?

2022-09-20 13:54 UTC, danielle-dsouza commented
> This pr was fixed yesterday, can we merge it?

Oops I might be mistaken, but didn't we discuss that we would wait for the new button designs before merging the sign up button?

2022-09-21 05:08 UTC, HakimSkaik commented
Ohh I thought we were addressing the buttons on the card, since the sign up button is a separate button?

2022-09-22 00:35 UTC, danielle-dsouza commented
> Ohh I thought we were addressing the buttons on the card, since the sign up button is a separate button?

Ah no I think let's pause on all the buttons. The home card buttons might be getting reworked too (she was exploring making one yellow and the other purple iirc). We'll wait till this weekend since she said that's likely when she'd be able to finish!

2022-09-30 21:36 UTC, HakimSkaik commented
any changes on this pr?

2022-10-02 04:15 UTC, HakimSkaik commented
@danielle-dsouza finally all conflicts are resolved, please review it thank youu

2022-10-02 16:32 UTC, danielle-dsouza commented
Hey @HakimSkaik I think something may have went wrong when you fixed the conflict - your branch is showing 67 commits  and almost 900 lines added/modified :thinking:

I'll try and fix it but I'm not 100% sure I know how!

2022-10-02 17:23 UTC, danielle-dsouza commented
I think it's good now. 🙏 

Do you mind glancing over the [code changes](https://github.com/cusec/2023/pull/26/files) and checking if everything looks right? One change I made during the merge fix was increasing the width when the side navigation enters from `768px` to `1180px`. Other than that I didn't touch anything!

2022-10-02 17:24 UTC, danielle-dsouza approved these changes

2022-10-02 22:01 UTC, merged