Created meet the team page
cusec/2023 pull request #55
Opened 2022-09-26 21:17 UTC by HakimSkaik

Matched the figma sketch

2022-09-26 21:19 UTC, HakimSkaik commented
![image](https://user-images.githubusercontent.com/98859282/192382630-f4bb3038-b5b4-4274-a980-f4c298eda27d.png)

2022-09-27 19:03 UTC, danielle-dsouza requested changes
Eyyy this is a good start! 

Let some comments - let me know if you have any questions. One quick request to use `Prettier` to format these files!

Also I noticed you created the first view of the `Teams` page but did not add the functionality where clicking on a dropdown tab reveals a div where the team members will be! Will you be doing that in this PR or should I create a follow up ticket?
<img width="477" alt="Screen Shot 2022-09-27 at 2 54 06 PM" src="https://user-images.githubusercontent.com/42760127/192611890-6cf18564-b325-4087-a721-a93f21eeced6.png">

2022-09-27 19:03 UTC, danielle-dsouza commented on src/sections/Team/Team.scss
> +}
Hmm why are we doing this? 🤔 If it's to align the text we should be manipulating `margin` and/or `padding` instead, or search up `display: flex` and look at how to vertically align text in a div.

If I'm misunderstanding something, sorry! Let me know if there's another reason you added this!

2022-09-27 19:03 UTC, danielle-dsouza commented on src/sections/Team/Team.tsx
> +            </li>
There's a lot of duplicated code so let's create a component nested in the `Teams` folder for the dropdown tab (so it should be in `/sections/Team/components`. The component will be something like
```
return (
     <li>
          <TheFontAwesomeIcon>
          <Paragraph inline>{text}</Paragraph>
     </li>
)
```

2022-09-27 19:03 UTC, danielle-dsouza commented on src/sections/Team/Team.scss
> +    background-color: rgb(140, 51, 188);
The color should also be `var(--primary-dark)`

2022-09-27 20:31 UTC, HakimSkaik commented on src/sections/Team/Team.scss
> +  font-style: normal;
Lines 6 and 7 were to match the same exact font as the figma file, but nonetheless I removed them

2022-09-27 20:47 UTC, HakimSkaik commented
Thank you for your review. And yes you can create a follow up ticket since I don't have any info of the team.

2022-09-27 20:48 UTC, HakimSkaik commented on src/sections/Team/Team.scss
> +}
The css disappears when I use Font awesome

2022-09-27 22:08 UTC, danielle-dsouza commented
> And yes you can create a follow up ticket since I don't have any info of the team.

Perfect thanks! Created #57 and #58 to handle the follow ups.

2022-09-27 22:39 UTC, HakimSkaik commented
I addressed your issues, please review it again, thank you.

2022-09-27 22:48 UTC, danielle-dsouza commented on src/sections/Team/Team.tsx
> +            ))}
Yesssss beautiful!

2022-09-27 22:48 UTC, danielle-dsouza commented on src/sections/Team/components/ExpandableDiv.scss
> +.roundedList:hover {
```suggestion
.RoundedList:hover {
```

2022-09-27 22:48 UTC, danielle-dsouza commented on src/sections/Team/components/ExpandableDiv.scss
> +}
Sorry not sure if you mentioned this but what is this for?

2022-09-27 22:49 UTC, danielle-dsouza commented on src/sections/Team/components/ExpandableDiv.scss
> +.roundedList:hover {
This style isn't being applied so if you'd like it to be we need to capitalize (or if it's not needed, we can remove it)!

2022-09-27 22:51 UTC, HakimSkaik commented on src/sections/Team/components/ExpandableDiv.scss
> +}
with:
![image](https://user-images.githubusercontent.com/98859282/192651368-424081a5-7602-4b92-b0a5-34655238dc05.png)
without:
![image](https://user-images.githubusercontent.com/98859282/192651412-ac91f961-e3a4-430d-9e05-1d00ac0115d4.png)

2022-09-27 22:53 UTC, HakimSkaik commented on src/sections/Team/components/ExpandableDiv.scss
> +.roundedList:hover {
deleted it, sorry did not notice

2022-09-28 05:06 UTC, danielle-dsouza commented on src/sections/Team/components/ExpandableDiv.scss
> +}
Ahhh okay I see. It definitely looks better with the smaller text. Hmm I feel iffy about using it just because I haven't used a percentage to control font size but let's go with it! I think a different class name relating to size - instead of position - would make more sense in this case - but I'll approve!

2022-09-28 05:07 UTC, danielle-dsouza approved these changes
Thanks for cleaning this up so quickly!

2022-09-30 12:36 UTC, merged