Replaced dummy images
cusec/2023 pull request #76
Opened 2022-10-26 22:21 UTC by HakimSkaik

Replaced all images to CUSEC conferences, please have a look, PS:  the images at the "what is CUSEC?" seem to be a bit crammed, we can handle that in another pr issue

2022-10-27 16:31 UTC, danielle-dsouza requested changes
Looks really good! Thanks for finding the images!

2022-10-27 16:31 UTC, danielle-dsouza commented on src/components/Image/Image.scss
> +  height: 100%;
```suggestion
  width: 100%;
  object-fit: cover;
```

2022-10-27 16:31 UTC, danielle-dsouza commented on src/components/Image/Image.scss
> +  height: 100%;
This should fix the cramped issue.

2022-10-28 05:03 UTC, danielle-dsouza commented on src/components/Image/Image.scss
>    width: 150%;
Is there a reason why we have 150%?

2022-10-30 01:00 UTC, HakimSkaik commented on src/components/Image/Image.scss
>    width: 150%;
it decreases the size of the other images significantly, making them look tiny next to the text

2022-10-30 01:01 UTC, HakimSkaik commented on src/components/Image/Image.scss
>    width: 150%;
150%: 
![image](https://user-images.githubusercontent.com/98859282/198858025-d6c6f643-0a93-4dfa-a303-e65e943da3c7.png)
100%:
![image](https://user-images.githubusercontent.com/98859282/198858036-ff08957a-87ce-4f0c-b8d2-d852c550632b.png)

2022-10-30 18:54 UTC, danielle-dsouza approved these changes

2022-10-30 18:54 UTC, danielle-dsouza commented on src/components/Image/Image.scss
>    width: 150%;
Thanks!

2022-10-30 18:57 UTC, merged